### ISSUE TITLE
Struggling to get JSONP

### ISSUE THREAD

**Issue by NeilWkz** [Cyclehack/cycle-map-stats#1]
I've poked around at the api a bit but as I know no python it's proving to be fruitless. 
I'm trying to get it to return JSONP (To get round the Cross-domain-origin issues we've been having).
I managed to get it to format the response to JSONP, but I can't get the api to pick up the callback that the frontend passes with the request. 
Angular dynamically assigns a callback to the request like "angular.callbacks._0" so it can easily pull the data into the scope of the app. 

I know that flask has a decorator function.

**Comment by skhutan** [comment]
Hmm I'll see what I can do by following this:
http://flask.pocoo.org/snippets/79/

**Comment by NeilWkz** [comment]
Awesome Works Like a Charm!
